experimentName: cancer_mirna_case
trialConcurrency: 1
maxExperimentDuration: 2h
maxTrialNumber: 1000
searchSpaceFile: cnn_search_space.json
useAnnotation: false
trialCommand: python nni_cnn_optimizer.py
trialCodeDirectory: .
trialGpuNumber: 0
tuner:
  name: Anneal
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  use_active_gpu: true
