experimentName: example_mnist
trialConcurrency: 2
maxExperimentDuration: 1h
maxTrialNumber: 100
searchSpaceFile: search_space.json
useAnnotation: false
trialCommand: python cnn_classifier.py
trialCodeDirectory: .
trialGpuNumber: 0
tuner:
  name: Anneal
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
