experimentName: cancer_mirna_case
trialConcurrency: 2
maxExperimentDuration: 1h
maxTrialNumber: 10
searchSpaceFile: search_space.json
useAnnotation: false
trialCommand: python ./src/models/cnn_classifier.py
trialCodeDirectory: ./../../.
trialGpuNumber: 0
tuner:
  name: Anneal
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
